import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class RRPolicy extends StatelessWidget {
  const RRPolicy({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        title: Text(
          'Returns & Refund Policy',
          style: GoogleFonts.inter(
            fontWeight: FontWeight.w600,
            color: const Color(0xFF111827),
            fontSize: 13,
          ),
        ),
        backgroundColor: Colors.white,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(  Icons.arrow_back),
          color: Color(0xFF111827),
          onPressed: () => Navigator.pop(context),
        ),
        centerTitle: true,
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(20),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Center(
                child: Text(
                  'Last Updated: December 1, 2025',
                  style: GoogleFonts.inter(
                    fontSize: 13,
                    color: const Color(0xFF4B5563),
                    height: 1.6,
                  ),
                ),
              ),
              const SizedBox(height: 24),
              const Divider(height: 1, color: Color(0xFFE5E7EB)),
              Text(
                'At Flyhub, we want you to be completely satisfied with your purchase. This policy outlines the conditions under which you can return products and receive refunds.',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 32),
              Text(
                '1. Return Window',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 12),
              Text(
                'Standard Products',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('8-14 days from delivery date for returns'),
              buildBulletPoint('Product must be unused, undamaged and in original packaging'),
              const SizedBox(height: 12),
              Text(
                'Drones & High-Value Items (above 10000)',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('8-14 days from delivery date for returns'),
              buildBulletPoint('Unopened box preferred for full refund'),
              buildBulletPoint('Opened box returns subject to inspection; may incur restocking fee'),
              const SizedBox(height: 12),
              Text(
                'Accessories & Parts',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('8-14 days from delivery date'),
              buildBulletPoint('Must be unused with original packaging and tags'),
              const SizedBox(height: 12),
              Text(
                'Non-Returnable Items',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Custom-built or modified drones'),
              buildBulletPoint('Software licenses and digital products'),
              buildBulletPoint('Opened batteries (safety regulations)'),
              buildBulletPoint('Items marked as "Final Sale" or "Non-Returnable"'),
              buildBulletPoint('Products damaged due to misuse or customer negligence'),
              const SizedBox(height: 32),
              Text(
                '2. Return Eligibility Conditions',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 12),
              Text(
                'You can return a product if:',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 12),
              buildBulletPoint('Defective or Damaged Product: Item received with manufacturing defects, product damaged during shipping, parts missing from the package'),
              buildBulletPoint('Wrong Product Received: Seller sent incorrect item, product does not match description or specifications'),
              buildBulletPoint('Product Not as Described: Significant variation from listing description, misleading product information'),
              buildBulletPoint('Change of Mind within 8-14 days: Unopened box with all original packaging, product unused and in resellable condition, all accessories, manuals, and components included'),
              const SizedBox(height: 32),
              Text(
                '3. Non-Returnable Conditions',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 12),
              Text(
                'You CANNOT Return if:',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 12),
              buildBulletPoint('8-14 day return window has expired'),
              buildBulletPoint('Product shows signs of use or damage'),
              buildBulletPoint('Original packaging is damaged or missing'),
              buildBulletPoint('Product is a custom order or personalized item'),
              buildBulletPoint('Batteries have been opened or installed'),
              buildBulletPoint('Serial numbers/stickers have been removed or tampered with'),
              buildBulletPoint('Drone has been flown (confirmed via flight logs)'),
              buildBulletPoint('Product was marked "Non-Returnable" at purchase'),
              const SizedBox(height: 32),
              Text(
                '4. How to Initiate a Return',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 12),
              Text(
                'Step 1: Request Return',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildNumberedItem(1, 'Open Flyhub app and go to My Orders'),
              buildNumberedItem(2, 'Select the order you want to return'),
              buildNumberedItem(3, 'Click Return/Refund Request'),
              buildNumberedItem(4, 'Choose reason for return'),
              buildNumberedItem(5, 'Upload photos/videos showing the issue for defective/damaged items'),
              buildNumberedItem(6, 'Submit request'),
              const SizedBox(height: 12),
              Text(
                'Step 2: Approval Process',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Seller has 24 hours to approve or reject your request'),
              buildBulletPoint('If approved, you’ll receive return instructions'),
              buildBulletPoint('If rejected, you can escalate to Flyhub support'),
              const SizedBox(height: 12),
              Text(
                'Step 3: Return Shipping',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Seller’s Fault (defective/wrong item): Free return pickup scheduled'),
              buildBulletPoint('Buyer’s Fault (change of mind): You arrange and pay for return shipping'),
              buildBulletPoint('Pack item securely in original packaging'),
              buildBulletPoint('Attach return shipping label if provided'),
              const SizedBox(height: 12),
              Text(
                'Step 4: Inspection & Refund',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Seller inspects returned item within 2 working days'),
              buildBulletPoint('Refund processed within 3-5 working days after inspection'),
              buildBulletPoint('You’ll receive confirmation via email and app notification'),
              const SizedBox(height: 32),
              Text(
                '5. Return Shipping Costs',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 12),
              Text(
                'Seller’s Responsibility (FREE for you)',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Defective or damaged product'),
              buildBulletPoint('Wrong item sent'),
              buildBulletPoint('Missing parts or accessories'),
              buildBulletPoint('Product not as described'),
              const SizedBox(height: 12),
              Text(
                'Your Responsibility',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Change of mind returns'),
              buildBulletPoint('Buyer’s remorse'),
              buildBulletPoint('Ordered wrong product by mistake'),
              const SizedBox(height: 12),
              Text(
                'Return Shipping Charges',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('150 for standard items (deducted from refund)'),
              buildBulletPoint('250 for drones and large items (deducted from refund)'),
              const SizedBox(height: 32),
              Text(
                '6. Refund Methods & Timeline',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 12),
              Text(
                'Refund Amount',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              Text(
                'Full Refund: Product Price + Shipping',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Defective, damaged or wrong product'),
              buildBulletPoint('Seller’s error'),
              const SizedBox(height: 12),
              Text(
                'Partial Refund: Product Price Only',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Change of mind returns'),
              buildBulletPoint('Original shipping charges non-refundable'),
              buildBulletPoint('Return shipping cost deducted'),
              const SizedBox(height: 12),
              Text(
                'Refund with Deductions',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Opened box on high-value items: 10% restocking fee'),
              buildBulletPoint('Damaged packaging: 5-15% deduction'),
              buildBulletPoint('Missing accessories: Cost of missing items deducted'),
              const SizedBox(height: 12),
              Text(
                'Refund Timeline',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              Text(
                'Processing Time',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Seller inspection: 2 working days from receiving return'),
              buildBulletPoint('Refund approval: 1 working day'),
              buildBulletPoint('Total: 3-5 working days from seller receiving returned item'),
              const SizedBox(height: 12),
              Text(
                'Refund Method',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              Text(
                'Original Payment Method',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Credit/Debit Card: 5-7 business days'),
              buildBulletPoint('UPI/Net Banking: 3-5 business days'),
              buildBulletPoint('Flyhub Wallet: Instant credited immediately'),
              buildBulletPoint('Cash on Delivery: Bank transfer (provide bank details)'),
              const SizedBox(height: 12),
              Text(
                'Flyhub Wallet Option',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Get instant refund to Flyhub Wallet'),
              buildBulletPoint('Use for future purchases'),
              buildBulletPoint('5% bonus credit on wallet refunds (promotional)'),
              const SizedBox(height: 32),
              Text(
                '7. Replacement vs Refund',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 12),
              Text(
                'When You Can Get Replacement:',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Defective product within 8-14 days'),
              buildBulletPoint('Wrong item received'),
              buildBulletPoint('Damaged during shipping'),
              const SizedBox(height: 12),
              Text(
                'Replacement Process',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildNumberedItem(1, 'Request replacement instead of refund during return request'),
              buildNumberedItem(2, 'Return defective/wrong item'),
              buildNumberedItem(3, 'Replacement shipped once return is received and verified'),
              buildNumberedItem(4, 'No additional shipping charges'),
              const SizedBox(height: 12),
              Text(
                'Replacement Availability',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Subject to stock availability'),
              buildBulletPoint('If out of stock, full refund issued'),
              buildBulletPoint('Replacement ships within 3 working days of verification'),
              const SizedBox(height: 32),
              Text(
                '8. Damaged or Defective Items',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 12),
              Text(
                'Report Immediately:',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Within 48 hours of delivery'),
              buildBulletPoint('Take clear photos/videos of damage'),
              buildBulletPoint('Do not use or further damage the product'),
              buildBulletPoint('Report through Flyhub app with evidence'),
              const SizedBox(height: 12),
              Text(
                'What to Photograph:',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Outer package damage'),
              buildBulletPoint('Product damage from all angles'),
              buildBulletPoint('Missing parts or accessories'),
              buildBulletPoint('Serial number/product label'),
              buildBulletPoint('Packing materials showing poor packaging'),
              const SizedBox(height: 12),
              Text(
                'Resolution:',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Free return pickup arranged'),
              buildBulletPoint('Full refund including shipping costs'),
              buildBulletPoint('Or immediate replacement if available'),
              buildBulletPoint('No restocking fees or deductions'),
              const SizedBox(height: 32),
              Text(
                '9. Rental Equipment Returns',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 12),
              Text(
                'Rental Return Process',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Must return within 24 hours of rental end date'),
              buildBulletPoint('Use prepaid return label provided'),
              buildBulletPoint('Pack equipment securely in original packaging'),
              buildBulletPoint('Drop off at courier location or schedule pickup'),
              const SizedBox(height: 12),
              Text(
                'Rental Deposit Refund',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Security deposit held during rental period'),
              buildBulletPoint('Refunded within 3-5 working days after equipment inspection'),
              buildBulletPoint('Full refund if no damage'),
              const SizedBox(height: 12),
              Text(
                'Damage Deductions',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Minor wear: No deduction'),
              buildBulletPoint('Scratches/cosmetic damage: 500-2000 deduction'),
              buildBulletPoint('Functional damage: Repair cost deducted'),
              buildBulletPoint('Lost/stolen equipment: Full equipment cost deducted'),
              const SizedBox(height: 12),
              Text(
                'Late Return Fees',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('500 per day for first 3 days'),
              buildBulletPoint('1000 per day after 3 days'),
              buildBulletPoint('After 7 days: Considered lost, full cost charged'),
              const SizedBox(height: 32),
              Text(
                '10. Cancellations',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 12),
              Text(
                'Before Dispatch',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('You can cancel anytime before seller ships the order'),
              buildBulletPoint('Full refund with no cancellation fees'),
              buildBulletPoint('Instant refund to original payment method'),
              const SizedBox(height: 12),
              Text(
                'How to Cancel',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Go to My Orders in Flyhub app'),
              buildBulletPoint('Select order and click Cancel Order'),
              buildBulletPoint('Choose cancellation reason'),
              buildBulletPoint('Confirm cancellation'),
              const SizedBox(height: 12),
              Text(
                'After Dispatch',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Once order is shipped, cancellation not possible'),
              buildBulletPoint('You can refuse delivery; return shipping & restocking fees apply'),
              buildBulletPoint('Or receive and return within 8-14 days as per return policy'),
              const SizedBox(height: 12),
              Text(
                'Seller Cancellation',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('If seller cancels your order: Full refund including shipping charges'),
              buildBulletPoint('Compensation of 100 Flyhub Wallet credit'),
              buildBulletPoint('Seller may face penalty'),
              const SizedBox(height: 32),
              Text(
                '11. Quality Check Returns',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 12),
              Text(
                'DOA (Dead on Arrival)',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Product doesn’t work out of the box'),
              buildBulletPoint('Report within 48 hours'),
              buildBulletPoint('Free return and full refund'),
              buildBulletPoint('Or immediate replacement, no questions asked'),
              const SizedBox(height: 12),
              Text(
                'Manufacturing Defects',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Discovered within 8-14 days: Free return, full refund or replacement'),
              buildBulletPoint('Seller bears all costs'),
              buildBulletPoint('After 8-14 days: Covered under manufacturer warranty'),
              buildBulletPoint('Contact brand service center or Flyhub can assist'),
              const SizedBox(height: 32),
              Text(
                '12. Opened vs Unopened Returns',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 12),
              Text(
                'Unopened Returns',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Original packaging sealed and intact'),
              buildBulletPoint('Full refund minus return shipping if change of mind'),
              buildBulletPoint('No restocking fees'),
              const SizedBox(height: 12),
              Text(
                'Opened Returns',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              Text(
                'Inspected but Unused',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('10% restocking fee on items above 10000'),
              buildBulletPoint('5% restocking fee on items under 10000'),
              buildBulletPoint('All accessories must be present'),
              const SizedBox(height: 8),
              buildBulletPoint('Used/Damaged: Return rejected or reduced refund based on condition'),
              buildBulletPoint('Seller provides detailed condition report'),
              const SizedBox(height: 32),
              Text(
                '13. Disputed Returns',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 12),
              Text(
                'If Seller Rejects Your Return',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Contact Flyhub customer support'),
              buildBulletPoint('Provide evidence (photos, videos, communications)'),
              buildBulletPoint('Flyhub mediates between buyer and seller'),
              buildBulletPoint('Resolution within 5-7 working days'),
              const SizedBox(height: 12),
              Text(
                'If Return Goes Missing',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Report within 24 hours of shipping'),
              buildBulletPoint('Provide tracking details'),
              buildBulletPoint('Flyhub files claim with courier'),
              buildBulletPoint('Refund processed once investigation completes'),
              const SizedBox(height: 12),
              Text(
                'If Seller Claims Item Damaged',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Seller must provide proof (photos/videos)'),
              buildBulletPoint('You can dispute with counter-evidence'),
              buildBulletPoint('Flyhub reviews both sides'),
              buildBulletPoint('Fair resolution based on evidence'),
              const SizedBox(height: 32),
              Text(
                '14. Warranty Information',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 12),
              Text(
                'Flyhub Protection (Optional Purchase)',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              Text(
                'What It Covers:',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Accidental damage within 1 year'),
              buildBulletPoint('Extended return window: 30 days'),
              buildBulletPoint('Free replacements for defects'),
              buildBulletPoint('Priority customer support'),
              const SizedBox(height: 8),
              Text(
                'Cost:',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('5% of product price'),
              buildBulletPoint('One-time fee at checkout'),
              const SizedBox(height: 12),
              Text(
                'Manufacturer Warranty',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('All branded products come with manufacturer warranty'),
              buildBulletPoint('Duration varies by brand: 6 months to 2 years'),
              buildBulletPoint('Warranty card included with product'),
              buildBulletPoint('Claim directly with brand or through Flyhub assistance'),
              const SizedBox(height: 32),
              Text(
                '15. Exceptions & Special Cases',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 12),
              Text(
                'During Sales/Promotions',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Same return policy applies'),
              buildBulletPoint('No special restrictions'),
              buildBulletPoint('Sale items are returnable unless marked "Final Sale"'),
              const SizedBox(height: 12),
              Text(
                'Pre-Orders',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Can cancel before product ships'),
              buildBulletPoint('After delivery, standard 8-14 day return applies'),
              const SizedBox(height: 12),
              Text(
                'Combo/Bundle Offers',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Must return entire bundle'),
              buildBulletPoint('Cannot return individual items from bundle'),
              buildBulletPoint('All items must be unused and in original packaging'),
              const SizedBox(height: 32),
              Text(
                '16. Customer Support for Returns',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 12),
              Text(
                'For Return Queries',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              Text(
                'Email: returns@flyhub.com',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              Text(
                'Phone: 919003992693',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              Text(
                'Hours: Monday - Friday, 9:00 AM - 6:00 PM IST',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 12),
              Text(
                'Track Return Status',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 8),
              buildBulletPoint('Flyhub app: My Orders > Returns'),
              buildBulletPoint('Real-time status updates'),
              buildBulletPoint('Email and SMS notifications'),
              const SizedBox(height: 32),
              const Divider(height: 1, color: Color(0xFFE5E7EB)),
              const SizedBox(height: 16),
              Text(
                'Note: This Returns & Refund Policy should be read in conjunction with Flyhub’s Shipping Policy and Terms of Service.',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: const Color(0xFF4B5563),
                  height: 1.6,
                ),
              ),
              const SizedBox(height: 32),
            ],
          ),
        ),
      ),
    );
  }

  Widget buildBulletPoint(String text) {
    return Padding(
      padding: const EdgeInsets.only(left: 16, bottom: 8),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(
            padding: const EdgeInsets.only(top: 8, right: 8),
            child: Text('•', style: TextStyle(color: const Color(0xFF4B5563), fontSize: 13)),
          ),
          Expanded(
            child: Text(
              text,
              style: GoogleFonts.inter(
                fontSize: 13,
                color: const Color(0xFF4B5563),
                height: 1.5,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget buildNumberedItem(int number, String text) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            '$number.',
            style: GoogleFonts.inter(
              fontSize: 13,
              color: const Color(0xFF4B5563),
              height: 1.6,
            ),
          ),
          const SizedBox(width: 8),
          Expanded(
            child: Text(
              text,
              style: GoogleFonts.inter(
                fontSize: 13,
                color: const Color(0xFF4B5563),
                height: 1.5,
              ),
            ),
          ),
        ],
      ),
    );
  }
}