// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfIaBqLW1JMUP-LEI2rLdD8leEZV5gD9M',
    appId: '1:40959779123:web:77134ad5885303f9bc9e46',
    messagingSenderId: '40959779123',
    projectId: 'flyhub-c99ec',
    authDomain: 'flyhub-c99ec.firebaseapp.com',
    storageBucket: 'flyhub-c99ec.firebasestorage.app',
    measurementId: 'G-T7JS0WV55D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_dHHixveEiqYs48mIj7bJzvVgOva8SrI',
    appId: '1:40959779123:android:ae35fb35ef78e058bc9e46',
    messagingSenderId: '40959779123',
    projectId: 'flyhub-c99ec',
    storageBucket: 'flyhub-c99ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcFVZXWR22eHz3d0ggH3xqA86wq60EOt4',
    appId: '1:40959779123:ios:5e0e0c6a8d6b0112bc9e46',
    messagingSenderId: '40959779123',
    projectId: 'flyhub-c99ec',
    storageBucket: 'flyhub-c99ec.firebasestorage.app',
    androidClientId: '40959779123-0im8hc5tebf2icvlpti5gb1cafm7plrg.apps.googleusercontent.com',
    iosClientId: '40959779123-vdhj2aqd2r0kjqpliu212q5njrg10qg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flyhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcFVZXWR22eHz3d0ggH3xqA86wq60EOt4',
    appId: '1:40959779123:ios:5e0e0c6a8d6b0112bc9e46',
    messagingSenderId: '40959779123',
    projectId: 'flyhub-c99ec',
    storageBucket: 'flyhub-c99ec.firebasestorage.app',
    androidClientId: '40959779123-0im8hc5tebf2icvlpti5gb1cafm7plrg.apps.googleusercontent.com',
    iosClientId: '40959779123-vdhj2aqd2r0kjqpliu212q5njrg10qg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flyhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfIaBqLW1JMUP-LEI2rLdD8leEZV5gD9M',
    appId: '1:40959779123:web:933ab7b20909ea70bc9e46',
    messagingSenderId: '40959779123',
    projectId: 'flyhub-c99ec',
    authDomain: 'flyhub-c99ec.firebaseapp.com',
    storageBucket: 'flyhub-c99ec.firebasestorage.app',
    measurementId: 'G-2PSBPSPDR0',
  );

}